// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/sio_package_description.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface SioPackageDescriptionRequest {
  type: string;
  name: string;
  version: string;
}

export interface SioPackageDescriptionResponse {
  success: boolean;
  error: string;
  description: Description | undefined;
}

export interface Website {
  blog: string;
  github: string;
}

export interface Author {
  name: string;
  email: string;
  website: Website | undefined;
}

export interface Description {
  name: string;
  version: string;
  license: string;
  type: string;
  vendor: string;
  vendorUrl: { [key: string]: string };
  description: { [key: string]: string };
  url: { [key: string]: string };
  support: string;
  author: Author | undefined;
}

export interface Description_VendorUrlEntry {
  key: string;
  value: string;
}

export interface Description_DescriptionEntry {
  key: string;
  value: string;
}

export interface Description_UrlEntry {
  key: string;
  value: string;
}

function createBaseSioPackageDescriptionRequest(): SioPackageDescriptionRequest {
  return { type: "", name: "", version: "" };
}

export const SioPackageDescriptionRequest: MessageFns<SioPackageDescriptionRequest> = {
  encode(message: SioPackageDescriptionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.version !== "") {
      writer.uint32(26).string(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioPackageDescriptionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioPackageDescriptionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.version = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioPackageDescriptionRequest {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
    };
  },

  toJSON(message: SioPackageDescriptionRequest): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioPackageDescriptionRequest>, I>>(base?: I): SioPackageDescriptionRequest {
    return SioPackageDescriptionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioPackageDescriptionRequest>, I>>(object: I): SioPackageDescriptionRequest {
    const message = createBaseSioPackageDescriptionRequest();
    message.type = object.type ?? "";
    message.name = object.name ?? "";
    message.version = object.version ?? "";
    return message;
  },
};

function createBaseSioPackageDescriptionResponse(): SioPackageDescriptionResponse {
  return { success: false, error: "", description: undefined };
}

export const SioPackageDescriptionResponse: MessageFns<SioPackageDescriptionResponse> = {
  encode(message: SioPackageDescriptionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== "") {
      writer.uint32(18).string(message.error);
    }
    if (message.description !== undefined) {
      Description.encode(message.description, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioPackageDescriptionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioPackageDescriptionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = Description.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioPackageDescriptionResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      description: isSet(object.description) ? Description.fromJSON(object.description) : undefined,
    };
  },

  toJSON(message: SioPackageDescriptionResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.description !== undefined) {
      obj.description = Description.toJSON(message.description);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioPackageDescriptionResponse>, I>>(base?: I): SioPackageDescriptionResponse {
    return SioPackageDescriptionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioPackageDescriptionResponse>, I>>(
    object: I,
  ): SioPackageDescriptionResponse {
    const message = createBaseSioPackageDescriptionResponse();
    message.success = object.success ?? false;
    message.error = object.error ?? "";
    message.description = (object.description !== undefined && object.description !== null)
      ? Description.fromPartial(object.description)
      : undefined;
    return message;
  },
};

function createBaseWebsite(): Website {
  return { blog: "", github: "" };
}

export const Website: MessageFns<Website> = {
  encode(message: Website, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blog !== "") {
      writer.uint32(10).string(message.blog);
    }
    if (message.github !== "") {
      writer.uint32(18).string(message.github);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Website {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWebsite();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.blog = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.github = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Website {
    return {
      blog: isSet(object.blog) ? globalThis.String(object.blog) : "",
      github: isSet(object.github) ? globalThis.String(object.github) : "",
    };
  },

  toJSON(message: Website): unknown {
    const obj: any = {};
    if (message.blog !== "") {
      obj.blog = message.blog;
    }
    if (message.github !== "") {
      obj.github = message.github;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Website>, I>>(base?: I): Website {
    return Website.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Website>, I>>(object: I): Website {
    const message = createBaseWebsite();
    message.blog = object.blog ?? "";
    message.github = object.github ?? "";
    return message;
  },
};

function createBaseAuthor(): Author {
  return { name: "", email: "", website: undefined };
}

export const Author: MessageFns<Author> = {
  encode(message: Author, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.website !== undefined) {
      Website.encode(message.website, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Author {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.website = Website.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Author {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      website: isSet(object.website) ? Website.fromJSON(object.website) : undefined,
    };
  },

  toJSON(message: Author): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.website !== undefined) {
      obj.website = Website.toJSON(message.website);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Author>, I>>(base?: I): Author {
    return Author.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Author>, I>>(object: I): Author {
    const message = createBaseAuthor();
    message.name = object.name ?? "";
    message.email = object.email ?? "";
    message.website = (object.website !== undefined && object.website !== null)
      ? Website.fromPartial(object.website)
      : undefined;
    return message;
  },
};

function createBaseDescription(): Description {
  return {
    name: "",
    version: "",
    license: "",
    type: "",
    vendor: "",
    vendorUrl: {},
    description: {},
    url: {},
    support: "",
    author: undefined,
  };
}

export const Description: MessageFns<Description> = {
  encode(message: Description, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.version !== "") {
      writer.uint32(18).string(message.version);
    }
    if (message.license !== "") {
      writer.uint32(26).string(message.license);
    }
    if (message.type !== "") {
      writer.uint32(34).string(message.type);
    }
    if (message.vendor !== "") {
      writer.uint32(42).string(message.vendor);
    }
    Object.entries(message.vendorUrl).forEach(([key, value]) => {
      Description_VendorUrlEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    Object.entries(message.description).forEach(([key, value]) => {
      Description_DescriptionEntry.encode({ key: key as any, value }, writer.uint32(58).fork()).join();
    });
    Object.entries(message.url).forEach(([key, value]) => {
      Description_UrlEntry.encode({ key: key as any, value }, writer.uint32(66).fork()).join();
    });
    if (message.support !== "") {
      writer.uint32(74).string(message.support);
    }
    if (message.author !== undefined) {
      Author.encode(message.author, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Description {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDescription();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.license = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.vendor = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = Description_VendorUrlEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.vendorUrl[entry6.key] = entry6.value;
          }
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          const entry7 = Description_DescriptionEntry.decode(reader, reader.uint32());
          if (entry7.value !== undefined) {
            message.description[entry7.key] = entry7.value;
          }
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          const entry8 = Description_UrlEntry.decode(reader, reader.uint32());
          if (entry8.value !== undefined) {
            message.url[entry8.key] = entry8.value;
          }
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.support = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.author = Author.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Description {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      license: isSet(object.license) ? globalThis.String(object.license) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      vendor: isSet(object.vendor) ? globalThis.String(object.vendor) : "",
      vendorUrl: isObject(object.vendorUrl)
        ? Object.entries(object.vendorUrl).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      description: isObject(object.description)
        ? Object.entries(object.description).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      url: isObject(object.url)
        ? Object.entries(object.url).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      support: isSet(object.support) ? globalThis.String(object.support) : "",
      author: isSet(object.author) ? Author.fromJSON(object.author) : undefined,
    };
  },

  toJSON(message: Description): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.license !== "") {
      obj.license = message.license;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.vendor !== "") {
      obj.vendor = message.vendor;
    }
    if (message.vendorUrl) {
      const entries = Object.entries(message.vendorUrl);
      if (entries.length > 0) {
        obj.vendorUrl = {};
        entries.forEach(([k, v]) => {
          obj.vendorUrl[k] = v;
        });
      }
    }
    if (message.description) {
      const entries = Object.entries(message.description);
      if (entries.length > 0) {
        obj.description = {};
        entries.forEach(([k, v]) => {
          obj.description[k] = v;
        });
      }
    }
    if (message.url) {
      const entries = Object.entries(message.url);
      if (entries.length > 0) {
        obj.url = {};
        entries.forEach(([k, v]) => {
          obj.url[k] = v;
        });
      }
    }
    if (message.support !== "") {
      obj.support = message.support;
    }
    if (message.author !== undefined) {
      obj.author = Author.toJSON(message.author);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Description>, I>>(base?: I): Description {
    return Description.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Description>, I>>(object: I): Description {
    const message = createBaseDescription();
    message.name = object.name ?? "";
    message.version = object.version ?? "";
    message.license = object.license ?? "";
    message.type = object.type ?? "";
    message.vendor = object.vendor ?? "";
    message.vendorUrl = Object.entries(object.vendorUrl ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.description = Object.entries(object.description ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.url = Object.entries(object.url ?? {}).reduce<{ [key: string]: string }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = globalThis.String(value);
      }
      return acc;
    }, {});
    message.support = object.support ?? "";
    message.author = (object.author !== undefined && object.author !== null)
      ? Author.fromPartial(object.author)
      : undefined;
    return message;
  },
};

function createBaseDescription_VendorUrlEntry(): Description_VendorUrlEntry {
  return { key: "", value: "" };
}

export const Description_VendorUrlEntry: MessageFns<Description_VendorUrlEntry> = {
  encode(message: Description_VendorUrlEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Description_VendorUrlEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDescription_VendorUrlEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Description_VendorUrlEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Description_VendorUrlEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Description_VendorUrlEntry>, I>>(base?: I): Description_VendorUrlEntry {
    return Description_VendorUrlEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Description_VendorUrlEntry>, I>>(object: I): Description_VendorUrlEntry {
    const message = createBaseDescription_VendorUrlEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseDescription_DescriptionEntry(): Description_DescriptionEntry {
  return { key: "", value: "" };
}

export const Description_DescriptionEntry: MessageFns<Description_DescriptionEntry> = {
  encode(message: Description_DescriptionEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Description_DescriptionEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDescription_DescriptionEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Description_DescriptionEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Description_DescriptionEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Description_DescriptionEntry>, I>>(base?: I): Description_DescriptionEntry {
    return Description_DescriptionEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Description_DescriptionEntry>, I>>(object: I): Description_DescriptionEntry {
    const message = createBaseDescription_DescriptionEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseDescription_UrlEntry(): Description_UrlEntry {
  return { key: "", value: "" };
}

export const Description_UrlEntry: MessageFns<Description_UrlEntry> = {
  encode(message: Description_UrlEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Description_UrlEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDescription_UrlEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Description_UrlEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Description_UrlEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Description_UrlEntry>, I>>(base?: I): Description_UrlEntry {
    return Description_UrlEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Description_UrlEntry>, I>>(object: I): Description_UrlEntry {
    const message = createBaseDescription_UrlEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
