// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/sio_coder_dump.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "../google/protobuf/struct";

export const protobufPackage = "";

export interface SioCoderDumpRequest {
  content: { [key: string]: any } | undefined;
  path: string;
  diff: boolean;
}

export interface SioCoderDumpProgress {
  count: number;
  index: number;
  file: string;
}

export interface SioCoderDumpResponseFile {
  content: string;
  /** !< 可选 */
  diff: string;
}

export interface SioCoderDumpResponse {
  success: boolean;
  error: string;
  files: { [key: string]: SioCoderDumpResponseFile };
}

export interface SioCoderDumpResponse_FilesEntry {
  key: string;
  value: SioCoderDumpResponseFile | undefined;
}

function createBaseSioCoderDumpRequest(): SioCoderDumpRequest {
  return { content: undefined, path: "", diff: false };
}

export const SioCoderDumpRequest: MessageFns<SioCoderDumpRequest> = {
  encode(message: SioCoderDumpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== undefined) {
      Struct.encode(Struct.wrap(message.content), writer.uint32(10).fork()).join();
    }
    if (message.path !== "") {
      writer.uint32(18).string(message.path);
    }
    if (message.diff !== false) {
      writer.uint32(24).bool(message.diff);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioCoderDumpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioCoderDumpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.diff = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioCoderDumpRequest {
    return {
      content: isObject(object.content) ? object.content : undefined,
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      diff: isSet(object.diff) ? globalThis.Boolean(object.diff) : false,
    };
  },

  toJSON(message: SioCoderDumpRequest): unknown {
    const obj: any = {};
    if (message.content !== undefined) {
      obj.content = message.content;
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.diff !== false) {
      obj.diff = message.diff;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioCoderDumpRequest>, I>>(base?: I): SioCoderDumpRequest {
    return SioCoderDumpRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioCoderDumpRequest>, I>>(object: I): SioCoderDumpRequest {
    const message = createBaseSioCoderDumpRequest();
    message.content = object.content ?? undefined;
    message.path = object.path ?? "";
    message.diff = object.diff ?? false;
    return message;
  },
};

function createBaseSioCoderDumpProgress(): SioCoderDumpProgress {
  return { count: 0, index: 0, file: "" };
}

export const SioCoderDumpProgress: MessageFns<SioCoderDumpProgress> = {
  encode(message: SioCoderDumpProgress, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.count !== 0) {
      writer.uint32(8).uint32(message.count);
    }
    if (message.index !== 0) {
      writer.uint32(16).uint32(message.index);
    }
    if (message.file !== "") {
      writer.uint32(26).string(message.file);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioCoderDumpProgress {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioCoderDumpProgress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.count = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.file = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioCoderDumpProgress {
    return {
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      file: isSet(object.file) ? globalThis.String(object.file) : "",
    };
  },

  toJSON(message: SioCoderDumpProgress): unknown {
    const obj: any = {};
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.file !== "") {
      obj.file = message.file;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioCoderDumpProgress>, I>>(base?: I): SioCoderDumpProgress {
    return SioCoderDumpProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioCoderDumpProgress>, I>>(object: I): SioCoderDumpProgress {
    const message = createBaseSioCoderDumpProgress();
    message.count = object.count ?? 0;
    message.index = object.index ?? 0;
    message.file = object.file ?? "";
    return message;
  },
};

function createBaseSioCoderDumpResponseFile(): SioCoderDumpResponseFile {
  return { content: "", diff: "" };
}

export const SioCoderDumpResponseFile: MessageFns<SioCoderDumpResponseFile> = {
  encode(message: SioCoderDumpResponseFile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.content !== "") {
      writer.uint32(10).string(message.content);
    }
    if (message.diff !== "") {
      writer.uint32(18).string(message.diff);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioCoderDumpResponseFile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioCoderDumpResponseFile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.diff = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioCoderDumpResponseFile {
    return {
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      diff: isSet(object.diff) ? globalThis.String(object.diff) : "",
    };
  },

  toJSON(message: SioCoderDumpResponseFile): unknown {
    const obj: any = {};
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.diff !== "") {
      obj.diff = message.diff;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioCoderDumpResponseFile>, I>>(base?: I): SioCoderDumpResponseFile {
    return SioCoderDumpResponseFile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioCoderDumpResponseFile>, I>>(object: I): SioCoderDumpResponseFile {
    const message = createBaseSioCoderDumpResponseFile();
    message.content = object.content ?? "";
    message.diff = object.diff ?? "";
    return message;
  },
};

function createBaseSioCoderDumpResponse(): SioCoderDumpResponse {
  return { success: false, error: "", files: {} };
}

export const SioCoderDumpResponse: MessageFns<SioCoderDumpResponse> = {
  encode(message: SioCoderDumpResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== "") {
      writer.uint32(18).string(message.error);
    }
    Object.entries(message.files).forEach(([key, value]) => {
      SioCoderDumpResponse_FilesEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioCoderDumpResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioCoderDumpResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = SioCoderDumpResponse_FilesEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.files[entry3.key] = entry3.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioCoderDumpResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      files: isObject(object.files)
        ? Object.entries(object.files).reduce<{ [key: string]: SioCoderDumpResponseFile }>((acc, [key, value]) => {
          acc[key] = SioCoderDumpResponseFile.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: SioCoderDumpResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.files) {
      const entries = Object.entries(message.files);
      if (entries.length > 0) {
        obj.files = {};
        entries.forEach(([k, v]) => {
          obj.files[k] = SioCoderDumpResponseFile.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioCoderDumpResponse>, I>>(base?: I): SioCoderDumpResponse {
    return SioCoderDumpResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioCoderDumpResponse>, I>>(object: I): SioCoderDumpResponse {
    const message = createBaseSioCoderDumpResponse();
    message.success = object.success ?? false;
    message.error = object.error ?? "";
    message.files = Object.entries(object.files ?? {}).reduce<{ [key: string]: SioCoderDumpResponseFile }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = SioCoderDumpResponseFile.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseSioCoderDumpResponse_FilesEntry(): SioCoderDumpResponse_FilesEntry {
  return { key: "", value: undefined };
}

export const SioCoderDumpResponse_FilesEntry: MessageFns<SioCoderDumpResponse_FilesEntry> = {
  encode(message: SioCoderDumpResponse_FilesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      SioCoderDumpResponseFile.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioCoderDumpResponse_FilesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioCoderDumpResponse_FilesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = SioCoderDumpResponseFile.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioCoderDumpResponse_FilesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? SioCoderDumpResponseFile.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: SioCoderDumpResponse_FilesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = SioCoderDumpResponseFile.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioCoderDumpResponse_FilesEntry>, I>>(base?: I): SioCoderDumpResponse_FilesEntry {
    return SioCoderDumpResponse_FilesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioCoderDumpResponse_FilesEntry>, I>>(
    object: I,
  ): SioCoderDumpResponse_FilesEntry {
    const message = createBaseSioCoderDumpResponse_FilesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? SioCoderDumpResponseFile.fromPartial(object.value)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
