// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/sio_coder_generate.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface SioCoderGenerateRequest {
  path: string;
  output: string;
  files: string[];
}

export interface SioCoderGenerateProgress {
  count: number;
  index: number;
  file: string;
  write: boolean;
}

export interface SioCoderGenerateResponse {
  success: boolean;
  error: string;
}

function createBaseSioCoderGenerateRequest(): SioCoderGenerateRequest {
  return { path: "", output: "", files: [] };
}

export const SioCoderGenerateRequest: MessageFns<SioCoderGenerateRequest> = {
  encode(message: SioCoderGenerateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    if (message.output !== "") {
      writer.uint32(18).string(message.output);
    }
    for (const v of message.files) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioCoderGenerateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioCoderGenerateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.output = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.files.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioCoderGenerateRequest {
    return {
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      output: isSet(object.output) ? globalThis.String(object.output) : "",
      files: globalThis.Array.isArray(object?.files) ? object.files.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: SioCoderGenerateRequest): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.output !== "") {
      obj.output = message.output;
    }
    if (message.files?.length) {
      obj.files = message.files;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioCoderGenerateRequest>, I>>(base?: I): SioCoderGenerateRequest {
    return SioCoderGenerateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioCoderGenerateRequest>, I>>(object: I): SioCoderGenerateRequest {
    const message = createBaseSioCoderGenerateRequest();
    message.path = object.path ?? "";
    message.output = object.output ?? "";
    message.files = object.files?.map((e) => e) || [];
    return message;
  },
};

function createBaseSioCoderGenerateProgress(): SioCoderGenerateProgress {
  return { count: 0, index: 0, file: "", write: false };
}

export const SioCoderGenerateProgress: MessageFns<SioCoderGenerateProgress> = {
  encode(message: SioCoderGenerateProgress, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.count !== 0) {
      writer.uint32(8).uint32(message.count);
    }
    if (message.index !== 0) {
      writer.uint32(16).uint32(message.index);
    }
    if (message.file !== "") {
      writer.uint32(26).string(message.file);
    }
    if (message.write !== false) {
      writer.uint32(32).bool(message.write);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioCoderGenerateProgress {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioCoderGenerateProgress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.count = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.file = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.write = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioCoderGenerateProgress {
    return {
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      file: isSet(object.file) ? globalThis.String(object.file) : "",
      write: isSet(object.write) ? globalThis.Boolean(object.write) : false,
    };
  },

  toJSON(message: SioCoderGenerateProgress): unknown {
    const obj: any = {};
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.file !== "") {
      obj.file = message.file;
    }
    if (message.write !== false) {
      obj.write = message.write;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioCoderGenerateProgress>, I>>(base?: I): SioCoderGenerateProgress {
    return SioCoderGenerateProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioCoderGenerateProgress>, I>>(object: I): SioCoderGenerateProgress {
    const message = createBaseSioCoderGenerateProgress();
    message.count = object.count ?? 0;
    message.index = object.index ?? 0;
    message.file = object.file ?? "";
    message.write = object.write ?? false;
    return message;
  },
};

function createBaseSioCoderGenerateResponse(): SioCoderGenerateResponse {
  return { success: false, error: "" };
}

export const SioCoderGenerateResponse: MessageFns<SioCoderGenerateResponse> = {
  encode(message: SioCoderGenerateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== "") {
      writer.uint32(18).string(message.error);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioCoderGenerateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioCoderGenerateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioCoderGenerateResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
    };
  },

  toJSON(message: SioCoderGenerateResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioCoderGenerateResponse>, I>>(base?: I): SioCoderGenerateResponse {
    return SioCoderGenerateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioCoderGenerateResponse>, I>>(object: I): SioCoderGenerateResponse {
    const message = createBaseSioCoderGenerateResponse();
    message.success = object.success ?? false;
    message.error = object.error ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
