// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/sio_package_install.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Description } from "./sio_package_description";

export const protobufPackage = "";

export interface SioPackageInstallRequest {
  path: string;
}

export interface SioPackageInstallProgress {
  count: number;
  index: number;
  file: string;
}

export interface SioPackageInstallResponse {
  success: boolean;
  error: string;
  description: Description | undefined;
}

function createBaseSioPackageInstallRequest(): SioPackageInstallRequest {
  return { path: "" };
}

export const SioPackageInstallRequest: MessageFns<SioPackageInstallRequest> = {
  encode(message: SioPackageInstallRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioPackageInstallRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioPackageInstallRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioPackageInstallRequest {
    return { path: isSet(object.path) ? globalThis.String(object.path) : "" };
  },

  toJSON(message: SioPackageInstallRequest): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioPackageInstallRequest>, I>>(base?: I): SioPackageInstallRequest {
    return SioPackageInstallRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioPackageInstallRequest>, I>>(object: I): SioPackageInstallRequest {
    const message = createBaseSioPackageInstallRequest();
    message.path = object.path ?? "";
    return message;
  },
};

function createBaseSioPackageInstallProgress(): SioPackageInstallProgress {
  return { count: 0, index: 0, file: "" };
}

export const SioPackageInstallProgress: MessageFns<SioPackageInstallProgress> = {
  encode(message: SioPackageInstallProgress, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.count !== 0) {
      writer.uint32(8).uint32(message.count);
    }
    if (message.index !== 0) {
      writer.uint32(16).uint32(message.index);
    }
    if (message.file !== "") {
      writer.uint32(26).string(message.file);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioPackageInstallProgress {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioPackageInstallProgress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.count = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.index = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.file = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioPackageInstallProgress {
    return {
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      file: isSet(object.file) ? globalThis.String(object.file) : "",
    };
  },

  toJSON(message: SioPackageInstallProgress): unknown {
    const obj: any = {};
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.file !== "") {
      obj.file = message.file;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioPackageInstallProgress>, I>>(base?: I): SioPackageInstallProgress {
    return SioPackageInstallProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioPackageInstallProgress>, I>>(object: I): SioPackageInstallProgress {
    const message = createBaseSioPackageInstallProgress();
    message.count = object.count ?? 0;
    message.index = object.index ?? 0;
    message.file = object.file ?? "";
    return message;
  },
};

function createBaseSioPackageInstallResponse(): SioPackageInstallResponse {
  return { success: false, error: "", description: undefined };
}

export const SioPackageInstallResponse: MessageFns<SioPackageInstallResponse> = {
  encode(message: SioPackageInstallResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.error !== "") {
      writer.uint32(18).string(message.error);
    }
    if (message.description !== undefined) {
      Description.encode(message.description, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SioPackageInstallResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSioPackageInstallResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = Description.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SioPackageInstallResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      description: isSet(object.description) ? Description.fromJSON(object.description) : undefined,
    };
  },

  toJSON(message: SioPackageInstallResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.description !== undefined) {
      obj.description = Description.toJSON(message.description);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SioPackageInstallResponse>, I>>(base?: I): SioPackageInstallResponse {
    return SioPackageInstallResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SioPackageInstallResponse>, I>>(object: I): SioPackageInstallResponse {
    const message = createBaseSioPackageInstallResponse();
    message.success = object.success ?? false;
    message.error = object.error ?? "";
    message.description = (object.description !== undefined && object.description !== null)
      ? Description.fromPartial(object.description)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
