# this file is used to describe allwinner`s d1h
LFBGA337:
    type: "LFBGA"
    count: 337
    number:
        row: 20
        column: 20
    ignore:
        - A: ["5", "7", "9", "10", "12", "14", "16"]
        - D: ["8", "11", "14"]
        - E: ["1", "8", "11", "14", "20"]
        - F: ["8", "11", "14"]
        - G: ["1", "20"]
        - H: ["4", "5", "6", "15", "16", "17"]
        - J: ["1", "20"]
        - K: ["20"]
        - L: ["1", "4", "5", "6", "15", "16", "17"]
        - M: ["1", "20"]
        - P: ["1", "4", "5", "6", "15", "16", "17", "20"]
        - R: ["8", "11", "14"]
        - T: ["1", "8", "11", "14", "20"]
        - U: ["8", "11", "14"]
        - Y: ["5", "7", "10", "12", "14", "16"]
