# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright (C) 2022-2023 xqyjlj<xqyjlj@126.com>
#
# @author      xqyjlj
# @file        package.yml
#
# Change Logs:
# Date           Author       Notes
# ------------   ----------   -----------------------------------------------
# 2023-01-08     xqyjlj       initial version
#

# this file is used to describe allwinner`s d1h
LFBGA337:
    type: "LFBGA"
    count: 337
    number:
        row: 20
        column: 20
    ignore:
        - A: ["5", "7", "9", "10", "12", "14", "16"]
        - D: ["8", "11", "14"]
        - E: ["1", "8", "11", "14", "20"]
        - F: ["8", "11", "14"]
        - G: ["1", "20"]
        - H: ["4", "5", "6", "15", "16", "17"]
        - J: ["1", "20"]
        - K: ["20"]
        - L: ["1", "4", "5", "6", "15", "16", "17"]
        - M: ["1", "20"]
        - P: ["1", "4", "5", "6", "15", "16", "17", "20"]
        - R: ["8", "11", "14"]
        - T: ["1", "8", "11", "14", "20"]
        - U: ["8", "11", "14"]
        - Y: ["5", "7", "10", "12", "14", "16"]
