# Licensed under the GNU General Public License v. 3 (the "License")
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.gnu.org/licenses/gpl-3.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright (C) 2022-2024 xqyjlj<xqyjlj@126.com>
#
# @author      xqyjlj
# @file        project.yml
#
# Change Logs:
# Date           Author       Notes
# ------------   ----------   -----------------------------------------------
# 2024-06-29     xqyjlj       initial version
#

$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  version:
    type: string
    pattern: "^(?:v|V)?\\d+\\.\\d+\\.\\d+$"
  name:
    type: string
    minLength: 1
  vendor:
    type: string
    minLength: 1
  targetChip:
    type: string
    minLength: 1
  configs:
    type: object
  modules:
    type: array
    items:
      type: string
  gen:
    type: object
    properties:
      copyLibrary:
        type: boolean
      linker:
        type: object
        properties:
          defaultHeapSize:
            type: integer
          defaultStackSize:
            type: integer
      useToolchainsPackage:
        type: boolean
      hal:
        type: string
        minLength: 1
      halVersion:
        type: string
      builder:
        type: string
      builderVersion:
        type: string
      toolchains:
        type: string
      toolchainsVersion:
        type: string
required: [version, name, vendor, targetChip]
