# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\xqyjlj\Documents\git\github\csplink\csp\widget\ui\grid_property_ip.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GridPropertyIp(object):
    def setupUi(self, GridPropertyIp):
        GridPropertyIp.setObjectName("GridPropertyIp")
        GridPropertyIp.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(GridPropertyIp)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView_property = TableView(GridPropertyIp)
        self.tableView_property.setObjectName("tableView_property")
        self.verticalLayout.addWidget(self.tableView_property)

        self.retranslateUi(GridPropertyIp)
        QtCore.QMetaObject.connectSlotsByName(GridPropertyIp)

    def retranslateUi(self, GridPropertyIp):
        _translate = QtCore.QCoreApplication.translate
        GridPropertyIp.setWindowTitle(_translate("GridPropertyIp", "GridPropertyIp"))
from qfluentwidgets import TableView
