# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\xqyjlj\Documents\git\github\csplink\csp\widget\ui\grid_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GridMode(object):
    def setupUi(self, GridMode):
        GridMode.setObjectName("GridMode")
        GridMode.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(GridMode)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(GridMode)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_gridModeIo = GridModeIo(self.page_1)
        self.widget_gridModeIo.setObjectName("widget_gridModeIo")
        self.verticalLayout_2.addWidget(self.widget_gridModeIo)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(GridMode)
        QtCore.QMetaObject.connectSlotsByName(GridMode)

    def retranslateUi(self, GridMode):
        _translate = QtCore.QCoreApplication.translate
        GridMode.setWindowTitle(_translate("GridMode", "GridMode"))
from widget.grid_mode_io import GridModeIo
