# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\xqyjlj\Documents\git\github\csplink\csp\widget\ui\grid_mode_io.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GridModeIo(object):
    def setupUi(self, GridModeIo):
        GridModeIo.setObjectName("GridModeIo")
        GridModeIo.resize(654, 355)
        self.verticalLayout = QtWidgets.QVBoxLayout(GridModeIo)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView_io = TableView(GridModeIo)
        self.tableView_io.setObjectName("tableView_io")
        self.verticalLayout.addWidget(self.tableView_io)

        self.retranslateUi(GridModeIo)
        QtCore.QMetaObject.connectSlotsByName(GridModeIo)

    def retranslateUi(self, GridModeIo):
        _translate = QtCore.QCoreApplication.translate
        GridModeIo.setWindowTitle(_translate("GridModeIo", "GridModeIo"))
from qfluentwidgets import TableView
