# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\xqyjlj\Documents\git\github\csplink\csp\widget\ui\mode_grid_io.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModeGridIo(object):
    def setupUi(self, ModeGridIo):
        ModeGridIo.setObjectName("ModeGridIo")
        ModeGridIo.resize(654, 355)
        self.verticalLayout = QtWidgets.QVBoxLayout(ModeGridIo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_search = LineEdit(ModeGridIo)
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView_io = TableView(ModeGridIo)
        self.tableView_io.setObjectName("tableView_io")
        self.verticalLayout.addWidget(self.tableView_io)

        self.retranslateUi(ModeGridIo)
        QtCore.QMetaObject.connectSlotsByName(ModeGridIo)

    def retranslateUi(self, ModeGridIo):
        _translate = QtCore.QCoreApplication.translate
        ModeGridIo.setWindowTitle(_translate("ModeGridIo", "ModeGridIo"))
from qfluentwidgets import LineEdit, TableView
