# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\xqyjlj\Documents\git\github\csplink\csp\widget\ui\property_grid_ip.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PropertyGridIp(object):
    def setupUi(self, PropertyGridIp):
        PropertyGridIp.setObjectName("PropertyGridIp")
        PropertyGridIp.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(PropertyGridIp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView_property = TableView(PropertyGridIp)
        self.tableView_property.setObjectName("tableView_property")
        self.verticalLayout.addWidget(self.tableView_property)

        self.retranslateUi(PropertyGridIp)
        QtCore.QMetaObject.connectSlotsByName(PropertyGridIp)

    def retranslateUi(self, PropertyGridIp):
        _translate = QtCore.QCoreApplication.translate
        PropertyGridIp.setWindowTitle(_translate("PropertyGridIp", "PropertyGridIp"))
from qfluentwidgets import TableView
