# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\xqyjlj\Documents\git\github\csplink\csp\widget\ui\tree_module.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TreeModule(object):
    def setupUi(self, TreeModule):
        TreeModule.setObjectName("TreeModule")
        TreeModule.resize(529, 481)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TreeModule)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeView_modules = TreeView(TreeModule)
        self.treeView_modules.setObjectName("treeView_modules")
        self.horizontalLayout.addWidget(self.treeView_modules)

        self.retranslateUi(TreeModule)
        QtCore.QMetaObject.connectSlotsByName(TreeModule)

    def retranslateUi(self, TreeModule):
        _translate = QtCore.QCoreApplication.translate
        TreeModule.setWindowTitle(_translate("TreeModule", "TreeModule"))
from qfluentwidgets import TreeView
