//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSP.Modules.Pages.MCU.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSP.Modules.Pages.MCU.Resources.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /**
        /// * @file ${file}
        /// * @brief ${brief}
        /// * @author ${author}
        /// * @version 0.0
        /// * @date ${year}-${month}-${day} ${hour}:${minute}:${second}
        /// * @copyright Copyright © 2021-${year} misfra team
        /// * @SPDX-License-Identifier: Apache-2.0
        /// *
        /// * ************************************************************************************
        /// * @par ChangeLog:
        /// * &lt;table&gt;
        /// * &lt;tr&gt;&lt;th&gt;Date       &lt;th&gt;Version &lt;th&gt;Author            &lt;th&gt;Description
        /// * &lt;tr&gt;&lt;td&gt;${year}-${month}-${day} &lt;td&gt;0.0     &lt;td&gt;${author}               &lt;t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #ifdef __cplusplus
        ///}
        ///#endif
        ///
        ///#endif 的本地化字符串。
        /// </summary>
        internal static string HeaderEnd {
            get {
                return ResourceManager.GetString("HeaderEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #ifndef __${file}
        ///#define __${file}
        ///
        ///#ifdef __cplusplus
        ///extern &quot;C&quot; {
        ///#endif 的本地化字符串。
        /// </summary>
        internal static string HeaderStart {
            get {
                return ResourceManager.GetString("HeaderStart", resourceCulture);
            }
        }
    }
}
