# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\xqyjlj\Documents\git\github\csplink\csp\view\ui\code_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CodeView(object):
    def setupUi(self, CodeView):
        CodeView.setObjectName("CodeView")
        CodeView.resize(790, 567)
        self.verticalLayout = QtWidgets.QVBoxLayout(CodeView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabBar = TabBar(CodeView)
        self.tabBar.setObjectName("tabBar")
        self.verticalLayout.addWidget(self.tabBar)
        self.stackedWidget = QtWidgets.QStackedWidget(CodeView)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(CodeView)
        QtCore.QMetaObject.connectSlotsByName(CodeView)

    def retranslateUi(self, CodeView):
        _translate = QtCore.QCoreApplication.translate
        CodeView.setWindowTitle(_translate("CodeView", "CodeView"))
from qfluentwidgets import TabBar
