# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\xqyjlj\Desktop\csp\view\ui\chip_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chipView(object):
    def setupUi(self, chipView):
        chipView.setObjectName("chipView")
        chipView.resize(1342, 994)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(chipView)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = SimpleCardWidget(chipView)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeView = TreeView(self.frame)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_2.addWidget(self.treeView)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_2 = SimpleCardWidget(chipView)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = GraphicsViewPanZoom(self.frame_2)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(463, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolButtonZoomIn = ToolButton(self.widget_2)
        self.toolButtonZoomIn.setText("")
        self.toolButtonZoomIn.setObjectName("toolButtonZoomIn")
        self.horizontalLayout.addWidget(self.toolButtonZoomIn)
        self.toolButtonZoomReset = ToolButton(self.widget_2)
        self.toolButtonZoomReset.setText("")
        self.toolButtonZoomReset.setObjectName("toolButtonZoomReset")
        self.horizontalLayout.addWidget(self.toolButtonZoomReset)
        self.toolButtonZoomOut = ToolButton(self.widget_2)
        self.toolButtonZoomOut.setText("")
        self.toolButtonZoomOut.setObjectName("toolButtonZoomOut")
        self.horizontalLayout.addWidget(self.toolButtonZoomOut)
        spacerItem1 = QtWidgets.QSpacerItem(462, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 5)

        self.retranslateUi(chipView)
        QtCore.QMetaObject.connectSlotsByName(chipView)

    def retranslateUi(self, chipView):
        _translate = QtCore.QCoreApplication.translate
        chipView.setWindowTitle(_translate("chipView", "Form"))
from qfluentwidgets import SimpleCardWidget, ToolButton, TreeView
from widget.graphics_view_pan_zoom import GraphicsViewPanZoom
