# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\xqyjlj\Documents\git\github\csplink\csp\view\ui\code_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CodeView(object):
    def setupUi(self, CodeView):
        CodeView.setObjectName("CodeView")
        CodeView.resize(790, 567)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CodeView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cardWidget_file = SimpleCardWidget(CodeView)
        self.cardWidget_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardWidget_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cardWidget_file.setObjectName("cardWidget_file")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cardWidget_file)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget_file = TreeWidget(self.cardWidget_file)
        self.treeWidget_file.setObjectName("treeWidget_file")
        self.treeWidget_file.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.treeWidget_file)
        self.horizontalLayout.addWidget(self.cardWidget_file)
        self.frame_2 = SimpleCardWidget(CodeView)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget_code = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget_code.setObjectName("stackedWidget_code")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit = PlainTextEditCode(self.page)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        self.stackedWidget_code.addWidget(self.page)
        self.verticalLayout.addWidget(self.stackedWidget_code)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(CodeView)
        QtCore.QMetaObject.connectSlotsByName(CodeView)

    def retranslateUi(self, CodeView):
        _translate = QtCore.QCoreApplication.translate
        CodeView.setWindowTitle(_translate("CodeView", "CodeView"))
from qfluentwidgets import SimpleCardWidget, TreeWidget
from widget.plain_text_edit_code import PlainTextEditCode
