# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Users\xqyjlj\Documents\git\github\csplink\csp\view\ui\chip_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChipView(object):
    def setupUi(self, ChipView):
        ChipView.setObjectName("ChipView")
        ChipView.resize(1219, 967)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ChipView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_1 = QtWidgets.QSplitter(ChipView)
        self.splitter_1.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_1.setObjectName("splitter_1")
        self.frame = SimpleCardWidget(self.splitter_1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = TreeModule(self.frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2.addWidget(self.widget)
        self.frame_3 = SimpleCardWidget(self.splitter_1)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.frame_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitter_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_gridModeIo = GridModeIo(self.page)
        self.widget_gridModeIo.setObjectName("widget_gridModeIo")
        self.horizontalLayout_5.addWidget(self.widget_gridModeIo)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.page_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4.addWidget(self.widget_4)
        self.stackedWidget.addWidget(self.page_2)
        self.widget_propertyGridIo = GridPropertyIp(self.splitter_2)
        self.widget_propertyGridIo.setObjectName("widget_propertyGridIo")
        self.verticalLayout.addWidget(self.splitter_2)
        self.frame_2 = SimpleCardWidget(self.splitter_1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = GraphicsViewPanZoom(self.frame_2)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.widget_2 = QtWidgets.QWidget(self.frame_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(463, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolButton_zoomIn = ToolButton(self.widget_2)
        self.toolButton_zoomIn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolButton_zoomIn.setText("")
        self.toolButton_zoomIn.setObjectName("toolButton_zoomIn")
        self.horizontalLayout.addWidget(self.toolButton_zoomIn)
        self.toolButton_zoomReset = ToolButton(self.widget_2)
        self.toolButton_zoomReset.setText("")
        self.toolButton_zoomReset.setObjectName("toolButton_zoomReset")
        self.horizontalLayout.addWidget(self.toolButton_zoomReset)
        self.toolButton_zoomOut = ToolButton(self.widget_2)
        self.toolButton_zoomOut.setText("")
        self.toolButton_zoomOut.setObjectName("toolButton_zoomOut")
        self.horizontalLayout.addWidget(self.toolButton_zoomOut)
        spacerItem1 = QtWidgets.QSpacerItem(462, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_3.addWidget(self.splitter_1)

        self.retranslateUi(ChipView)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ChipView)

    def retranslateUi(self, ChipView):
        _translate = QtCore.QCoreApplication.translate
        ChipView.setWindowTitle(_translate("ChipView", "ChipView"))
from qfluentwidgets import SimpleCardWidget, ToolButton
from widget.graphics_view_pan_zoom import GraphicsViewPanZoom
from widget.grid_mode_io import GridModeIo
from widget.grid_property_ip import GridPropertyIp
from widget.tree_module import TreeModule
