# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sio_package_install.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'proto/sio_package_install.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import sio_package_description_pb2 as proto_dot_sio__package__description__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/sio_package_install.proto\x1a#proto/sio_package_description.proto\"(\n\x18SioPackageInstallRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"G\n\x19SioPackageInstallProgress\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\"^\n\x19SioPackageInstallResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12!\n\x0b\x64\x65scription\x18\x03 \x01(\x0b\x32\x0c.Descriptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sio_package_install_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIOPACKAGEINSTALLREQUEST']._serialized_start=72
  _globals['_SIOPACKAGEINSTALLREQUEST']._serialized_end=112
  _globals['_SIOPACKAGEINSTALLPROGRESS']._serialized_start=114
  _globals['_SIOPACKAGEINSTALLPROGRESS']._serialized_end=185
  _globals['_SIOPACKAGEINSTALLRESPONSE']._serialized_start=187
  _globals['_SIOPACKAGEINSTALLRESPONSE']._serialized_end=281
# @@protoc_insertion_point(module_scope)
