# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sio_coder_generate.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'proto/sio_coder_generate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/sio_coder_generate.proto\"F\n\x17SioCoderGenerateRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06output\x18\x02 \x01(\t\x12\r\n\x05\x66iles\x18\x03 \x03(\t\"U\n\x18SioCoderGenerateProgress\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\r\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\x12\r\n\x05write\x18\x04 \x01(\x08\":\n\x18SioCoderGenerateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sio_coder_generate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIOCODERGENERATEREQUEST']._serialized_start=34
  _globals['_SIOCODERGENERATEREQUEST']._serialized_end=104
  _globals['_SIOCODERGENERATEPROGRESS']._serialized_start=106
  _globals['_SIOCODERGENERATEPROGRESS']._serialized_end=191
  _globals['_SIOCODERGENERATERESPONSE']._serialized_start=193
  _globals['_SIOCODERGENERATERESPONSE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
