# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sio_package_description.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'proto/sio_package_description.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#proto/sio_package_description.proto\"K\n\x1cSioPackageDescriptionRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\"b\n\x1dSioPackageDescriptionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12!\n\x0b\x64\x65scription\x18\x03 \x01(\x0b\x32\x0c.Description\"\'\n\x07Website\x12\x0c\n\x04\x62log\x18\x01 \x01(\t\x12\x0e\n\x06github\x18\x02 \x01(\t\"@\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x19\n\x07website\x18\x03 \x01(\x0b\x32\x08.Website\"\x9f\x03\n\x0b\x44\x65scription\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07license\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0e\n\x06vendor\x18\x05 \x01(\t\x12.\n\tvendorUrl\x18\x06 \x03(\x0b\x32\x1b.Description.VendorUrlEntry\x12\x32\n\x0b\x64\x65scription\x18\x07 \x03(\x0b\x32\x1d.Description.DescriptionEntry\x12\"\n\x03url\x18\x08 \x03(\x0b\x32\x15.Description.UrlEntry\x12\x0f\n\x07support\x18\t \x01(\t\x12\x17\n\x06\x61uthor\x18\n \x01(\x0b\x32\x07.Author\x1a\x30\n\x0eVendorUrlEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x44\x65scriptionEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a*\n\x08UrlEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sio_package_description_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DESCRIPTION_VENDORURLENTRY']._loaded_options = None
  _globals['_DESCRIPTION_VENDORURLENTRY']._serialized_options = b'8\001'
  _globals['_DESCRIPTION_DESCRIPTIONENTRY']._loaded_options = None
  _globals['_DESCRIPTION_DESCRIPTIONENTRY']._serialized_options = b'8\001'
  _globals['_DESCRIPTION_URLENTRY']._loaded_options = None
  _globals['_DESCRIPTION_URLENTRY']._serialized_options = b'8\001'
  _globals['_SIOPACKAGEDESCRIPTIONREQUEST']._serialized_start=39
  _globals['_SIOPACKAGEDESCRIPTIONREQUEST']._serialized_end=114
  _globals['_SIOPACKAGEDESCRIPTIONRESPONSE']._serialized_start=116
  _globals['_SIOPACKAGEDESCRIPTIONRESPONSE']._serialized_end=214
  _globals['_WEBSITE']._serialized_start=216
  _globals['_WEBSITE']._serialized_end=255
  _globals['_AUTHOR']._serialized_start=257
  _globals['_AUTHOR']._serialized_end=321
  _globals['_DESCRIPTION']._serialized_start=324
  _globals['_DESCRIPTION']._serialized_end=739
  _globals['_DESCRIPTION_VENDORURLENTRY']._serialized_start=595
  _globals['_DESCRIPTION_VENDORURLENTRY']._serialized_end=643
  _globals['_DESCRIPTION_DESCRIPTIONENTRY']._serialized_start=645
  _globals['_DESCRIPTION_DESCRIPTIONENTRY']._serialized_end=695
  _globals['_DESCRIPTION_URLENTRY']._serialized_start=697
  _globals['_DESCRIPTION_URLENTRY']._serialized_end=739
# @@protoc_insertion_point(module_scope)
