--
-- file automatically-generated by tool: [csp] version: [${{version}}] date: ${{date}}
--
add_rules("mode.debug", "mode.release")

set_project("${{project}}") -- set project name
set_version("0.0.0") -- set version
set_xmakever("2.7.9")

add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

includes("hal/xmake.lua")

add_requires("${{toolchains}}")
set_toolchains("@${{toolchains}}")

add_ldflags("-T${{link_script}}",
            {force = true})

target("${{project}}")
do
    set_kind("binary")
    set_warnings("allextra", "error")

    set_languages("c99")
    set_extension(".elf")
    add_deps("${{hal}}")

    add_rules("csp.bin")
    add_rules("csp.map")
    add_rules("csp.cpu")

    add_files("src/*.c")
end
target_end()
