--
-- file automatically-generated by tool: [csp] version: [${{version}}] date: ${{date}}
--

-- Set build rules. See more information at https://xmake.io/#/manual/custom_rule?id=modedebug
add_rules("mode.debug", "mode.release")
${{includes}}
set_project("${{project}}") -- Set project name
set_version("0.0.0") -- Set version
set_xmakever("2.7.9") -- Set minimal xmake version

-- Automatically update the generated compile_commandss.json
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

-- Set toolchains, which will be automatically downloaded and installed by xmake
add_requires("${{toolchains}}")
set_toolchains("@${{toolchains}}")
${{requires}}
-- Set linkscript
add_ldflags("-T${{linkscript}}", {force = true})

target("${{project}}")
do
    set_kind("binary")
${{warnings}}
    set_languages(${{languages}})
    set_extension(".elf")
    add_deps("${{hal}}")
${{deps}}
${{rules}}
${{includedirs}}
${{files}}
end
target_end()
